# Generated by Django 5.1.1 on 2024-09-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ambiente', models.CharField(max_length=15)),
                ('nombre_ambiente', models.CharField(max_length=100)),
                ('sede', models.CharField(choices=[('Principal', 'Principal'), ('Alternativa', 'Alternativa'), ('Granja', 'Granja')], max_length=100)),
            ],
            options={
                'db_table': 'Ambiente',
            },
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo_norma', models.IntegerField(blank=True, null=True, verbose_name='Código de la norma')),
                ('unidad_competencia', models.CharField(max_length=500)),
                ('duracion_estimada', models.CharField(help_text='Duración estimada para lograr el aprendizaje', max_length=50, verbose_name='Duración estimada (horas)')),
                ('resultado_aprendizaje', models.TextField()),
            ],
            options={
                'db_table': 'Competencia',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('numero_celular', models.CharField(max_length=15)),
                ('numero_cedula', models.CharField(max_length=15, unique=True)),
                ('competencias_imparte', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Instructor',
            },
        ),
        migrations.CreateModel(
            name='ProgramaFormacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_programa', models.CharField(max_length=15)),
                ('nombre_programa', models.CharField(max_length=50)),
                ('jornada', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=50)),
                ('numero_ficha', models.CharField(max_length=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'db_table': 'ProgramaFormacion',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('numero_cedula', models.CharField(max_length=20, unique=True)),
                ('numero_celular', models.CharField(max_length=20)),
                ('correo_institucional', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
