# Generated by Django 5.1.1 on 2024-09-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competencia',
            name='codigo_norma',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
