# Generated by Django 5.1.1 on 2024-09-25 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_administrador_groups_administrador_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
