# Generated by Django 4.2 on 2025-02-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de la fromación')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la formación')),
                ('dias_recurrencia', models.JSONField()),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
    ]
