# Generated by Django 4.2 on 2025-02-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarios', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendar',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.ambiente'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.competencia'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.instructor'),
        ),
        migrations.AddField(
            model_name='calendar',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.programaformacion'),
        ),
    ]
