# Generated by Django 5.1.1 on 2024-09-29 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calendarios', '0001_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calamb',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.competencia'),
        ),
        migrations.AddField(
            model_name='calamb',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.instructor'),
        ),
        migrations.AddField(
            model_name='calamb',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.programaformacion'),
        ),
        migrations.AddField(
            model_name='calinst',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.ambiente'),
        ),
        migrations.AddField(
            model_name='calinst',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.competencia'),
        ),
        migrations.AddField(
            model_name='calinst',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.programaformacion'),
        ),
        migrations.AddField(
            model_name='calpf',
            name='ambiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.ambiente'),
        ),
        migrations.AddField(
            model_name='calpf',
            name='competencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.competencia'),
        ),
        migrations.AddField(
            model_name='calpf',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.instructor'),
        ),
    ]
