# Generated by Django 5.1.1 on 2024-09-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarios', '0002_initial'),
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calinst',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='calinst',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='calinst',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='calpf',
            name='ambiente',
        ),
        migrations.RemoveField(
            model_name='calpf',
            name='competencia',
        ),
        migrations.RemoveField(
            model_name='calpf',
            name='instructor',
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de la fromación')),
                ('end', models.DateTimeField(blank=True, null=True, verbose_name='Fin de la formación')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.ambiente')),
                ('competencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.competencia')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.instructor')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.programaformacion')),
            ],
            options={
                'db_table': 'calendar',
            },
        ),
        migrations.DeleteModel(
            name='CalAmb',
        ),
        migrations.DeleteModel(
            name='CalInst',
        ),
        migrations.DeleteModel(
            name='CalPF',
        ),
    ]
